# Generated by Django 2.0.2 on 2018-05-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cost_nonmember',
            new_name='cost_non_member',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_for',
            new_name='hosted_by',
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
