# Generated by Django 2.0.2 on 2018-05-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180529_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='signup_start_fresher',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
