# Generated by Django 2.0.2 on 2018-05-19 11:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_eventsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2018, 5, 19, 11, 45, 34, 474577, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventsignup',
            unique_together={('user', 'event')},
        ),
    ]
