# Generated by Django 2.0.2 on 2018-06-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180529_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_livestream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='has_photography',
            field=models.BooleanField(default=False),
        ),
    ]
