# Generated by Django 2.0.2 on 2018-06-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180603_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='photography_consent',
            field=models.BooleanField(default=False),
        ),
    ]
