# Generated by Django 2.0.2 on 2018-06-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='transaction_token',
            field=models.TextField(blank=True),
        ),
    ]
