# Generated by Django 2.0.2 on 2018-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20180606_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='eventsignup',
            unique_together=set(),
        ),
    ]
