# Generated by Django 2.0.2 on 2018-06-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20180606_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
