# Generated by Django 2.0.2 on 2018-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180606_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='unsigned_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
