# Generated by Django 2.0.2 on 2018-06-07 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventsignup_unsigned_up_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='<a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> allowed, but no raw HTML. Examples: **bold**, *italic*, indent 4 spaces for a code block.')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(default=django.utils.timezone.now)),
                ('signup_form', models.URLField()),
                ('signup_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('signup_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('requires_attendance', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('for_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
