# Generated by Django 2.0.2 on 2018-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
