# Generated by Django 2.0.2 on 2018-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20180608_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
