# Generated by Django 2.2 on 2019-05-01 15:37

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    EventSignup = apps.get_model("events", "EventSignup")
    Ticket = apps.get_model("events", "Ticket")

    for signup in EventSignup.objects.all():
        # Create a Ticket object if it has transaction info in it and set its status
        if signup.transaction_token:
            status = Ticket.REFUNDED if signup.refund_token else Ticket.COMPLETE
            ticket = Ticket(charge_id=signup.transaction_token, status=status)

            ticket.save()


def reverse_func(apps, schema_editor):
    # Delete all Ticket objects
    Ticket = apps.get_model("events", "Ticket")

    Ticket.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsignup',
            name='ticket',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Ticket'),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
