# Generated by Django 2.2 on 2019-05-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_eventsignup_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsignup',
            name='refund_token',
        ),
        migrations.RemoveField(
            model_name='eventsignup',
            name='transaction_token',
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Ticket'),
        ),
    ]
