# Generated by Django 2.2 on 2019-05-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20190501_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('C', 'Complete'), ('R', 'Refunded'), ('P', 'In progress'), ('N', 'Created')], default='N', max_length=1),
        ),
    ]
