# Generated by Django 2.2 on 2019-05-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20190502_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup', to='events.Ticket'),
        ),
    ]
