# Generated by Django 2.2 on 2019-05-02 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_func(apps, schema_editor):
    Ticket = apps.get_model("events", "Ticket")
    EventSignup = apps.get_model("events", "EventSignup")

    for ticket in Ticket.objects.all():
        try:
            signup = EventSignup.objects.get(ticket=ticket)
            ticket.user = signup.user
            ticket.save()
        except EventSignup.DoesNotExist:
            pass


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0023_auto_20190502_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(forward_func, reverse_func)
    ]
