# Generated by Django 2.2 on 2019-05-02 11:23
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forward_func(apps, schema_editor):
    Ticket = apps.get_model("events", "Ticket")

    Ticket.objects.filter(user=None).all().delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_ticket_user'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func)
    ]
