# Generated by Django 2.2 on 2019-05-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_remove_eventsignup_photography_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='comment',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
