# Generated by Django 2.2 on 2019-05-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_eventsignup_comment_added_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsignup',
            old_name='comment_added_at',
            new_name='commented_at',
        ),
    ]
