# Generated by Django 2.2.1 on 2019-05-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_auto_20190516_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_platform',
            new_name='platform',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='tournament_platform_other',
            new_name='platform_other',
        ),
    ]
