# Generated by Django 2.2.1 on 2019-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_auto_20190516_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='platform',
            field=models.CharField(choices=[('S', 'Steam'), ('B', 'Battle.NET'), ('L', 'League of Legends'), ('N', 'Nintendo Switch'), ('X', 'Xbox One'), ('P', 'Playstation 4'), ('O', 'Other')], help_text='If "other" please specify', max_length=1),
        ),
    ]
