# Generated by Django 2.2.1 on 2019-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20190516_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='games',
            field=models.TextField(blank=True),
        ),
    ]
