# Generated by Django 2.2.1 on 2019-05-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_tournament_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='games',
            field=models.TextField(blank=True, help_text='A comma separated list of the game(s) played in this tournament'),
        ),
    ]
