# Generated by Django 2.2.1 on 2019-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20190516_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='games',
            field=models.CharField(blank=True, help_text='A comma separated list of the game(s) played in this tournament', max_length=1024),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
