# Generated by Django 2.2.1 on 2019-05-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_auto_20190516_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsignup',
            name='is_unsigned_up',
            field=models.BooleanField(default=False),
        ),
    ]
