# Generated by Django 2.2.1 on 2019-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_tournamentsignup_is_unsigned_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsignup',
            name='platform_tag',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
