# Generated by Django 2.2.1 on 2019-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_auto_20190516_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentsignup',
            name='platform_tag',
            field=models.CharField(max_length=256),
        ),
    ]
