# Generated by Django 2.2.1 on 2019-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_auto_20190520_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='platform',
            field=models.CharField(choices=[('S', 'Steam'), ('B', 'Battle.NET'), ('L', 'League of Legends'), ('N', 'Nintendo Switch'), ('X', 'Xbox Live'), ('P', 'Playstation Network'), ('O', 'Other')], help_text='If "other" please specify', max_length=1),
        ),
    ]
