# Generated by Django 2.2.1 on 2019-05-21 09:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_auto_20190520_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentsignup',
            name='commented_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
