# Generated by Django 2.2.6 on 2019-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_tournamentsignup_commented_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='seating_lock_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
