# Generated by Django 2.0.2 on 2018-06-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seating',
            name='table',
        ),
    ]
