# Generated by Django 2.0.2 on 2018-05-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventsignup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='eventsignup',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventsignup',
            name='member',
        ),
        migrations.DeleteModel(
            name='EventSignup',
        ),
    ]
