# Generated by Django 2.2.6 on 2019-10-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0003_auto_20191018_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seating',
            name='seat_id',
            field=models.CharField(max_length=5),
        ),
    ]
