# Generated by Django 2.0.2 on 2018-05-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwcs_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warwickgguser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
