# Generated by Django 2.0.2 on 2018-06-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uwcs_auth', '0003_warwickgguser_privacy_policy_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warwickgguser',
            name='privacy_policy_read',
        ),
    ]
