# Generated by Django 2.2 on 2019-05-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwcs_auth', '0004_remove_warwickgguser_privacy_policy_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='warwickgguser',
            name='battle_net_user',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='warwickgguser',
            name='steam_user',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
