# Generated by Django 2.2 on 2019-05-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwcs_auth', '0005_auto_20190503_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warwickgguser',
            name='battle_net_user',
            field=models.CharField(blank=True, max_length=32, verbose_name='Battle.NET user'),
        ),
    ]
